<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UseCase Suites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4ae31d2f-6af6-4fe0-8117-ee872320015f</testSuiteGuid>
   <testCaseLink>
      <guid>1060f1cb-4e63-4eb6-b300-123deb156278</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Studio Assist/Generate Code/Generate Code - UseCase 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed28676-5553-4a97-b30f-3675455b50f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b369554-b124-4ed6-ba51-9383ac6e0fc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1192b948-ea7c-4404-941c-c6379790ed85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Studio Assist/DataDriven Test/Generate Script to create CSV</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ead018e1-11ed-4155-acbe-6548c6dd0ddc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Studio Assist/DataDriven Test/Generate Script for Datadriven Test</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87b2805d-6cbc-41b8-a563-92dbfe088f84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08ccf694-bc40-4b2a-8668-90878c077a5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48dbd796-7312-4335-8ea2-cb69ed96c2f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01a3bc66-1de4-46c2-b631-7987a8be3f3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da7894f1-3f97-4454-a771-89dcbfefb846</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Studio Assist/Generate Code/Generate Code - UseCase 4 optimized</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c81fcb15-063c-4976-a81c-67ab35c1b2e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1046cfbb-97a7-452a-be52-8999b0faf5db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83c0a1e6-c988-413b-b6ff-0becc9b3ca47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Studio Assist/DataDriven Test/Login With Data Driven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ded1dee-ca79-42e4-aac7-cbb79ce0720d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/logindata (1)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1ded1dee-ca79-42e4-aac7-cbb79ce0720d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>96cef149-83d6-484c-83c6-722d747b920b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ded1dee-ca79-42e4-aac7-cbb79ce0720d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>d3cc2b07-dff5-4327-a173-6eff39c956b6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
