<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>success</name>
   <tag></tag>
   <elementGuidId>2ab5f737-5c76-4c2d-9553-67f881ef2472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-page']/div[2]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.status.alert.alert-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#contact-page >> internal:text=&quot;Success! Your details have been submitted successfully.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19a77cfb-6e3d-4763-89a8-e21a1511cafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status alert alert-success</value>
      <webElementGuid>7a7654ed-2806-4806-ad8d-f1850c254766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success! Your details have been submitted successfully.</value>
      <webElementGuid>f6791e99-bfcb-457e-90c0-e40347e2b2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-page&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;contact-form&quot;]/div[@class=&quot;status alert alert-success&quot;]</value>
      <webElementGuid>82ab5bb3-3e50-45a9-bf42-c6cf1c5139e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-page']/div[2]/div/div/div[2]</value>
      <webElementGuid>509bdbfe-e28a-4965-b96a-7e85399400f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get In Touch'])[1]/following::div[1]</value>
      <webElementGuid>77f94d90-76ed-44a2-91f0-3c1922d865d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::div[1]</value>
      <webElementGuid>70ad7897-919e-4d05-b26c-ce10d288c1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::div[1]</value>
      <webElementGuid>6b645505-b175-4e89-919f-79184a7eafef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback For Us'])[1]/preceding::div[2]</value>
      <webElementGuid>999354d9-b924-422f-afb9-1a38a3b46211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Success! Your details have been submitted successfully.']/parent::*</value>
      <webElementGuid>6da15183-47a6-4a05-84c2-7679f2a887a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>dc6ec893-11c2-4b01-9745-5294e8f2bc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Success! Your details have been submitted successfully.' or . = 'Success! Your details have been submitted successfully.')]</value>
      <webElementGuid>296a766a-6757-4860-81be-476de3a5fa98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
