<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Company</name>
   <tag></tag>
   <elementGuidId>ca8c23dc-c53b-4e5b-8e1c-e3b0405e8884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' footer-list ') and (position() = 1)]//h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.footer-list:nth-child(1) h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Company&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>951f9f52-101e-4259-bf11-98989eab42fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>bf9e18cf-90b9-499d-b837-022eb5cec408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b8f3b0d1c6b34c95c9b8625c3a45925</value>
      <webElementGuid>22a54a65-c50a-4b38-a425-05672701465a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' footer-list ') and (position() = 1)]//h5</value>
      <webElementGuid>39ced7f7-9cf3-415d-9242-87d592b1131b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' footer-list ') and (position() = 1)]//h5</value>
      <webElementGuid>fb9e9a4a-f616-417e-bde8-07332b1fda68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Company' or . = 'Company')]</value>
      <webElementGuid>64288472-665c-454c-8c8b-dc0574c06b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
